### ISSUE TITLE
Filename error in Makefile

### ISSUE THREAD

**Issue by acarnage** [stevenaldinger/decker-plugin#1]
There is a filename error in the make file : 

@decker $(BASE_DIR)/examples/plugin-schema-test.hcl

should be replaced by : 

@decker $(BASE_DIR)/examples/plugin-test.hcl

**Comment by acarnage** [comment]
I also observed the following error while attempting to use a custom helloworld plugin with the actual decker:kali docker image : 

plugin.Open("/plugins/hello/hello"): plugin was built with a different version of package internal/cpu

**Comment by stevenaldinger** [comment]
Thanks for catching these (and being interested in plugin development)! This whole thing likely needs an update, let me take a look tonight. I'll include better docs at the same time and make sure you're able to get started easily.

Thanks again!

**Comment by acarnage** [comment]
No problems ! 

i'll be pleased to add some plugins ! :)

**Comment by acarnage** [comment]
Hi !

Did you managed to have a look on the compatibility problem between this repo and decker core ? :)

**Comment by stevenaldinger** [comment]
Hey, sorry about the wait here. Life has been a bit hectic.

I needed to update some things in the actual core to make things easier to maintain and when I took a look at getting this repo working I got it 99% there but need to update _one_ more thing in core and then it'll be ready for you to play with. I followed some conventions with decker core but because of doing that golang doesn't let me import certain tools that are necessary but copying them into the decker-plugin directory makes it difficult to get dependencies imported properly since there's technically no "main" function.

I'll get back to you ASAP when I have a solution, sorry again for the time it's taken.

**Comment by acarnage** [comment]
> Hey, sorry about the wait here. Life has been a bit hectic.
> 
> I needed to update some things in the actual core to make things easier to maintain and when I took a look at getting this repo working I got it 99% there but need to update _one_ more thing in core and then it'll be ready for you to play with. I followed some conventions with decker core but because of doing that golang doesn't let me import certain tools that are necessary but copying them into the decker-plugin directory makes it difficult to get dependencies imported properly since there's technically no "main" function.
> 
> I'll get back to you ASAP when I have a solution, sorry again for the time it's taken.

No problems, take all the time needed ;)

**Comment by stevenaldinger** [comment]
When I originally wrote decker I only supported strings or a map of strings and that was it, which I handled with JSON encoding.

After spending hours on this tonight, the blocker ended up being the underlying library that allows for dynamic inputs (like a user choosing to input a list, string, or map without the coder knowing ahead of time and I tried about 8 hours straight to try to trick it into working and it's not going to budge.

The options I see are to encode/decode all the dynamic values before it gets to the plugin itself (which is extremely complex or I would've done that to begin with but golang is not dynamically typed which is the problem there again) OR adding a bunch of developer friendly documentation and steps to the core decker repo which is likely what I'll end up doing.

I really appreciate you bringing it to my attention, it's a pretty huge let down the design doesn't work though. The dynamic library is the same one Terraform uses so I assumed it'd be a good library but Terraform uses RPC (like most things) since golang "plugins" weren't a thing until recently.

Thanks for your patience, I'll do what I can ASAP again now.

**Comment by stevenaldinger** [comment]
@acarnage added some documentation, an example hello world plugin, and some build instructions to the core repo. If you give it a try let me know if you have any issues and definitely open up a PR if you're willing to share!

- [building-plugins](https://github.com/stevenaldinger/decker/blob/master/docs/building_plugins.md)
- [hello-world decker config](https://github.com/stevenaldinger/decker/blob/master/examples/hello-world.hcl)
- [hello_world plugin code](https://github.com/stevenaldinger/decker/tree/master/internal/app/decker/plugins/hello_world)

**Comment by acarnage** [comment]
@stevenaldinger  Thank you for the update ! I will give a try next week! :)
